# Makefile for 18-Graphs/programs/AirlineGraphUsingClasses
#****************************************************************

PROGRAMS = \
    AirlineGraph

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

AirlineGraph: AirlineGraph.o
	g++ $(LDOPTIONS) -o AirlineGraph AirlineGraph.o $(LIB)

AirlineGraph.o: AirlineGraph.cpp
	g++ $(CPPOPTIONS) -c AirlineGraph.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
