# Makefile for 08-RecursiveStrategies/programs/Snowflake
#****************************************************************

PROGRAMS = \
    Snowflake

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

Snowflake: Snowflake.o
	g++ $(LDOPTIONS) -o Snowflake Snowflake.o $(LIB)

Snowflake.o: Snowflake.cpp
	g++ $(CPPOPTIONS) -c Snowflake.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
