# Makefile for 03-Strings/programs/RepeatChar
#****************************************************************

PROGRAMS = \
    RepeatChar

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

RepeatChar: RepeatChar.o
	g++ $(LDOPTIONS) -o RepeatChar RepeatChar.o $(LIB)

RepeatChar.o: RepeatChar.cpp
	g++ $(CPPOPTIONS) -c RepeatChar.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
