# Makefile for 20-StrategiesForIteration/programs/ListMap
#****************************************************************

PROGRAMS = \
    ListMap

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

ListMap: ListMap.o
	g++ $(LDOPTIONS) -o ListMap ListMap.o $(LIB)

ListMap.o: ListMap.cpp
	g++ $(CPPOPTIONS) -c ListMap.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
