# Makefile for 01-OverviewOfC++/programs/DirectionTest
#****************************************************************

PROGRAMS = \
    DirectionTest

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

DirectionTest: DirectionTest.o direction.o
	g++ $(LDOPTIONS) -o DirectionTest DirectionTest.o direction.o $(LIB)

DirectionTest.o: DirectionTest.cpp direction.h
	g++ $(CPPOPTIONS) -c DirectionTest.cpp

direction.o: direction.cpp direction.h
	g++ $(CPPOPTIONS) -c direction.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
