# Makefile for 04-Streams/programs/PowerTable
#****************************************************************

PROGRAMS = \
    PowerTable

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

PowerTable: PowerTable.o
	g++ $(LDOPTIONS) -o PowerTable PowerTable.o $(LIB)

PowerTable.o: PowerTable.cpp
	g++ $(CPPOPTIONS) -c PowerTable.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
