# Makefile for 08-RecursiveStrategies/programs/Mondrian
#****************************************************************

PROGRAMS = \
    Mondrian

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

Mondrian: Mondrian.o
	g++ $(LDOPTIONS) -o Mondrian Mondrian.o $(LIB)

Mondrian.o: Mondrian.cpp
	g++ $(CPPOPTIONS) -c Mondrian.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
