# Makefile for 06-DesigningClasses/programs/PigLatin
#****************************************************************

PROGRAMS = \
    PigLatin

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

PigLatin: PigLatin.o
	g++ $(LDOPTIONS) -o PigLatin PigLatin.o $(LIB)

PigLatin.o: PigLatin.cpp
	g++ $(CPPOPTIONS) -c PigLatin.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
