# Makefile for 12-DynamicMemoryManagement/programs/BeaconsOfGondorRecursive
#****************************************************************

PROGRAMS = \
    BeaconsOfGondor

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

BeaconsOfGondor: BeaconsOfGondor.o
	g++ $(LDOPTIONS) -o BeaconsOfGondor BeaconsOfGondor.o $(LIB)

BeaconsOfGondor.o: BeaconsOfGondor.cpp
	g++ $(CPPOPTIONS) -c BeaconsOfGondor.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
