# Makefile for 07-IntroductionToRecursion/programs/BinarySearch
#****************************************************************

PROGRAMS = \
    BinarySearch

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

BinarySearch: BinarySearch.o
	g++ $(LDOPTIONS) -o BinarySearch BinarySearch.o $(LIB)

BinarySearch.o: BinarySearch.cpp
	g++ $(CPPOPTIONS) -c BinarySearch.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
