# Makefile for 04-Streams/programs/PrecisionExample
#****************************************************************

PROGRAMS = \
    PrecisionExample

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

PrecisionExample: PrecisionExample.o
	g++ $(LDOPTIONS) -o PrecisionExample PrecisionExample.o $(LIB)

PrecisionExample.o: PrecisionExample.cpp
	g++ $(CPPOPTIONS) -c PrecisionExample.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
