# Makefile for 03-Strings/programs/CaseConversion
#****************************************************************

PROGRAMS = \
    CaseConversion

CPPOPTIONS = -IStanfordCPPLib  -fvisibility-inlines-hidden
LDOPTIONS = -LStanfordCPPLib 
LIB = -lStanfordCPPLib

# ***************************************************************
# Entry to bring the package up to date
#    The "make all" entry should be the first real entry

all: $(PROGRAMS)

CaseConversion: CaseConversion.o
	g++ $(LDOPTIONS) -o CaseConversion CaseConversion.o $(LIB)

CaseConversion.o: CaseConversion.cpp
	g++ $(CPPOPTIONS) -c CaseConversion.cpp


# ***************************************************************
# Standard entries to remove files from the directories
#    tidy  -- eliminate unwanted files
#    clean -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out *.err

clean scratch: tidy
	rm -f *.o *.a $(PROGRAMS)
